image: node:12

stages:
- build
- test
- deploy

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn build:prod
  - cd dist && yarn install
  artifacts:
    paths:
    - app.yaml
    - manifest.yml
    - dist/
    when: on_success
  only:
  - master

jest_test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn test:ci --coverage
  coverage: '/All files\s*\|(?:\s*[\d\.]*\s*\|){3}\s*([\d\.]+)/'
  artifacts:
    paths:
    - coverage/lcov-report/
  only:
  - master

vulerability_scan:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn test:vulnerabilities
  only:
  - master
  allow_failure: true

deploy_heroku:
  stage: deploy
  dependencies:
  - build
  script:
  - mv Procfile -t dist/
  - git add dist/Procfile -f
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/goatdnf.git
  - git commit -m "Heroku deploy ${CI_COMMIT_SHORT_SHA}"
  - git subtree push --prefix dist heroku master
  environment:
    name: HEROKU_PROD
  only:
  - master

# Temporarily disabled until nodejs settings are configured
.deploy_gcp:
  stage: deploy
  image: google/cloud-sdk:latest
  dependencies:
  - build
  script:
  - echo $GCP_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud config set project ${GCP_PROJECT_ID}
  - mkdir www && mv dist/* www
  - gsutil rsync -d -r www gs://${GCP_APP_URL}
  - gsutil ls gs://${GCP_APP_URL}
  only:
  - master

.deploy_pws:
  stage: deploy
  dependencies:
  - build
  script:
  - mv manifest.yml -t dist/ && cd dist
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf api api.run.pivotal.io
  - ./cf auth
  - ./cf target -o $CF_ORG -s $CF_SPACE
  - ./cf push
  environment:
    name: PWS_PROD
  only:
  - master

# Use GitLab pages to host coverage report
pages:
  stage: deploy
  dependencies:
  - jest_test
  script:
  - mkdir -p public/coverage
  - mv coverage/lcov-report/* public/coverage
  artifacts:
    paths:
    - public
  only:
  - master
  allow_failure: true
