image: node:10

stages:
- test
- build
- deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
- yarn install

jest_test:
  stage: test
  script:
  - yarn test:ci

build:
  stage: build
  script:
  - yarn build --prod
  artifacts:
    paths:
    - app.yaml
    - manifest.yml
    - dist/

deploy_gcp:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
  - ''
  dependencies:
  - build
  script:
  - echo $GCP_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud config set project ${GCP_PROJECT_ID}
  - mkdir www && mv dist/* www
  - gsutil rsync -d -r www gs://${GCP_APP_URL}
  - gsutil ls gs://${GCP_APP_URL}

deploy_pws:
  stage: deploy
  before_script:
  - ''
  dependencies:
  - build
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf api api.run.pivotal.io
  - ./cf auth
  - ./cf push
  only:
  - master
