image: node:10

stages:
- build
- test
- deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - yarn install

build:
  stage: build
  script:
    - yarn build --prod
  artifacts:
    paths:
      - app.yaml
      - dist/

jest_test:
  stage: test
  script:
  - yarn test:ci

deploy_gcp:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - ''
  dependencies:
    - build
  script:
    - echo $GCP_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project ${GCP_PROJECT_ID}
    - mkdir www && mv dist/* www
    - gsutil rsync -d -r www gs://${GCP_APP_URL}/www
    - gsutil ls gs://${GCP_APP_URL}/www
