image: node:10

stages:
- test
- build
- deploy

jest_test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn test:ci --coverage
  coverage: '/All files\s*\|(?:\s*[\d\.]*\s*\|){3}\s*([\d\.]+)/'

vulerability_scan:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
    policy: pull
  script:
  - yarn install
  - yarn test:vulnerabilities
  allow_failure: true

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
    policy: pull
  script:
  - yarn install
  - yarn build --aot --prod && cd dist
  - yarn install
  artifacts:
    paths:
    - app.yaml
    - manifest.yml
    - dist/
    when: on_success

# Temporarily disabled until nodejs settings are configured
.deploy_gcp:
  stage: deploy
  image: google/cloud-sdk:latest
  dependencies:
  - build
  script:
  - echo $GCP_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud config set project ${GCP_PROJECT_ID}
  - mkdir www && mv dist/* www
  - gsutil rsync -d -r www gs://${GCP_APP_URL}
  - gsutil ls gs://${GCP_APP_URL}

deploy_pws:
  stage: deploy
  dependencies:
  - build
  script:
  - mv manifest.yml -t dist/ && cd dist
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf api api.run.pivotal.io
  - ./cf auth
  - ./cf target -o $CF_ORG -s $CF_SPACE
  - ./cf push
  only:
  - master
